import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually

  docs: [
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      link: {
        type: 'generated-index',
        slug: 'getting-started',
      },
      collapsed: false,
      items: [
        'getting-started/installation',
        'getting-started/configuration',
        'getting-started/typescript-support',
      ],
    },
  ],
  api: [
    {
      type: 'category',
      label: 'API Reference',
      link: {
        type: 'generated-index',
        slug: 'api',
      },
      items: [
        'api/createSyncedStore',
        'api/useStore',
        'api/actions',
        'api/getState',
        'api/setState',
        'api/subscribe',
        'api/persist',
        'api/rehydrate',
        'api/addMiddleware',
        'api/resetStore',
        'api/fetchFromDB',
        'api/saveToDB',
      ],
    },
    {
      type: 'category',
      label: 'Types',
      link: {
        type: 'doc',
        id: 'api/types/index',
      },
      items: [],
    }
  ],
};

export default sidebars;
